### ISSUE TITLE
Things we have learned today and how to apply them to our possible project

### ISSUE THREAD

**Issue by adriana6** [pi4-uiuc/PI4-Programming-Project#2]
**1. Branching repositories**
-Helps us be able to work on the project and see what others are doing. 

**2. Using R studio**
-We will analyze the data using R studio
-Importing libraries to download data off the web
-Saving our work to an online repository so that we can continue working on it from ANYWHERE
-Using dplyr to create new variables based off existing ones
-Data type coercion, e.g. str to POSITxs

**3. Looking at the variables we can only use: Air Pressure, Temperature and Humidity**

**4. The future plans for this project include doing visualizations of the data to see where various relations between different data types might exist. Further, we will do research on the type of data we are reseaching itself, so that we have more knowledge of what variables may or may not have actual relations (instead of looking at false positives, make sure that we are looking at real relations between variables). Finally, after doing all of these things, we will construct a model, likely statistical, which will take in input data and make predictions. We will then test this model on a set of test data.**

**5. Possible models: Higher temp means higher humidity.**

**6. Look at time frames of different variables and see if they break in times that overlap**

**7. Is the shape recognizable? Look at moving window of where it drops.**

**8. How can we tell the computer to identify machine is broken? It's not difficult to figure out...** 

**9. There are 3 stations that we can use. We should be able to experiment with them. Correction: Third station doesn't have a lot of observations.**

**10. The stations are very close to each other. They all use different machines. Perhaps same variables measured.**

**11. We will look at the two stations and compare their data throughout the seasons. Roughly a year of data.**

**Comment by dlebauer** [comment]
superseeded by #4
